substitutions:
  name: basen-bms-ble
  device_description: "Monitor a Basen Battery Management System via BLE"
  external_components_source: github://syssi/esphome-basen-bms@main
  mac_address: A4:C1:38:27:48:9A

esphome:
  name: ${name}
  comment: ${device_description}
  project:
    name: "syssi.esphome-basen-bms"
    version: 1.0.0

esp32:
  board: wemos_d1_mini32
  framework:
    type: esp-idf
    version: latest

external_components:
  - source: ${external_components_source}
    refresh: 0s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:
logger:
  level: VERY_VERBOSE
  logs:
    basen_bms_ble: VERY_VERBOSE
    ble_client: DEBUG
    esp32_ble: DEBUG
    esp32_ble_tracker: DEBUG
    scheduler: DEBUG
    component: DEBUG
    sensor: DEBUG
    api: DEBUG
    api.service: DEBUG

# If you don't use Home Assistant please remove this `api` section and uncomment the `mqtt` component!
api:

# The MQTT component is ESP-IDF compatible since ESPHome version 2022.4.0. If
# ESPHome suggests to use the arduino framework instead because of missing ESP-IDF
# framework support you should update your setup.
# mqtt:
#   broker: !secret mqtt_host
#   username: !secret mqtt_username
#   password: !secret mqtt_password
#   id: mqtt_client

esp32_ble_tracker:

ble_client:
  - mac_address: ${mac_address}
    id: client0

basen_bms_ble:
  - ble_client_id: client0
    id: bms0
    update_interval: 2s

binary_sensor:
  - platform: basen_bms_ble
    balancing:
      name: "${name} balancing"

sensor:
  - platform: basen_bms_ble
    total_voltage:
      name: "${name} total voltage"

text_sensor:
  - platform: basen_bms_ble
    errors:
      name: "${name} errors"

switch:
  - platform: ble_client
    ble_client_id: client0
    name: "${name} enable bluetooth connection"

  - platform: basen_bms_ble
    charging:
      name: "${name} charging"
